<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxDnSBQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxDnSBQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxDnSBQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxDnSBQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxDnSBQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxDnSBQ',
    'container.build_id' => '056e00d6',
    'container.build_time' => 1651430493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxDnSBQ');
